
version: 2

jobs:
  build:
    docker:
      # - image: rust:1
      - image: circleci/rust:1
    environment:
      TARGET: x86_64-unknown-linux-gnu
      PKG_CONFIG_ALLOW_CROSS: 1
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Install Target
          command: rustup target add x86_64-unknown-linux-musl
      - run:
          name: Install Dependencies
          command: sudo apt-get install libasound2-dev libssl-dev
      # - run:
      #     name: Calculate dependencies
      #     command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ echo $TARGET }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build debug
          # command: cargo build --all --all-targets
          command: cargo build --target "$TARGET"
      - run:
          name: Build
          command: cargo build --release --target "$TARGET"
      - store_artifacts:
          path: ./target/{{ echo $TARGET }}/release/listen-moe-cli
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/{{ echo $TARGET }}/.fingerprint
            - target/debug/{{ echo $TARGET }}/build
            - target/debug/{{ echo $TARGET }}/deps
            - target/release/{{ echo $TARGET }}/.fingerprint
            - target/release/{{ echo $TARGET }}/build
            - target/release/{{ echo $TARGET }}/deps
          key: v4-cargo-cache-{{ arch }}-{{ echo $TARGET }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Run all tests
          command: cargo test --target "$TARGET"
