name: Rust

on: [push]

jobs:
  build:
    
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Rust
      if: matrix.os == "macOS-latest"
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
